# Generated by Django 4.2.5 on 2023-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
